import React, { useState, useEffect } from 'react';
import { EuiButton, EuiText, EuiSpacer, EuiPanel, EuiLoadingSpinner, EuiCallOut } from '@elastic/eui';
import { Alert } from '../../common';
import { AlertsApiService } from '../services/api';

interface Props {
  alert: Alert;
  apiService: AlertsApiService;
  onAnalysisGenerated: (alertId: string, analysis: NonNullable<Alert['_source']['ai_analysis']>) => void;
  onError: (message: string) => void;
}

export const AiAnalysisTab: React.FC<Props> = ({ alert, apiService, onAnalysisGenerated, onError }) => {
  const [aiEnabled, setAiEnabled] = useState<boolean | null>(null);
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    apiService
      .fetchAiSettings()
      .then((res: any) => setAiEnabled(Boolean(res?.enabled && res?.configured)))
      .catch(() => setAiEnabled(false));
  }, []);

  const generate = async () => {
    try {
      setGenerating(true);
      const analysis: any = await apiService.analyzeAlert(alert._id);
      onAnalysisGenerated(alert._id, analysis);
    } catch (e: any) {
      onError(e?.body?.message || 'Failed to generate AI analysis');
    } finally {
      setGenerating(false);
    }
  };

  const analysis = alert._source.ai_analysis;

  if (aiEnabled === null) {
    return <EuiLoadingSpinner size="m" />;
  }

  return (
    <div>
      {!aiEnabled && (
        <EuiCallOut title="AI analysis is not configured" color="warning" iconType="alert">
          Set up an AI provider and API key under the AI Settings tab to enable this feature.
        </EuiCallOut>
      )}

      <EuiSpacer size="m" />

      {analysis ? (
        <EuiPanel paddingSize="m" hasBorder>
          <EuiText size="s" color="subdued">
            Generated by {analysis.provider}
            {analysis.model ? ` (${analysis.model})` : ''} at {new Date(analysis.generated_at).toLocaleString()}
          </EuiText>
          <EuiSpacer size="s" />
          <EuiText size="s" style={{ whiteSpace: 'pre-wrap' }}>
            {analysis.text}
          </EuiText>
        </EuiPanel>
      ) : (
        <EuiText size="s" color="subdued">
          No AI analysis generated yet for this alert.
        </EuiText>
      )}

      <EuiSpacer size="m" />
      <EuiButton size="s" onClick={generate} isLoading={generating} isDisabled={!aiEnabled}>
        {analysis ? 'Regenerate analysis' : 'Generate AI analysis'}
      </EuiButton>
    </div>
  );
};
