import React, { useState, useEffect } from 'react';
import { EuiButton, EuiText, EuiSpacer, EuiPanel, EuiLoadingSpinner, EuiCallOut } from '@elastic/eui';
import { AiAnalysis } from '../../common';
import { AlertsApiService } from '../services/api';

interface Props {
  analysis?: AiAnalysis;
  apiService: AlertsApiService;
  onGenerate: () => Promise<AiAnalysis>;
  onGenerated: (analysis: AiAnalysis) => void;
  onError: (message: string) => void;
  onToast?: (title: string, color: 'success' | 'danger' | 'primary', text?: string) => void;
  emptyMessage?: string;
}

/**
 * Generic AI-analysis panel: fetch/generate/display, with no knowledge of
 * whether it's summarizing an alert or a case - that's decided by the
 * caller's onGenerate function. See AlertFlyout / CaseFlyout for the two
 * concrete wirings.
 */
export const AiAnalysisTab: React.FC<Props> = ({
  analysis,
  apiService,
  onGenerate,
  onGenerated,
  onError,
  onToast,
  emptyMessage = 'No AI analysis generated yet.',
}) => {
  const [aiEnabled, setAiEnabled] = useState<boolean | null>(null);
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    apiService
      .fetchAiSettings()
      .then((res: any) => setAiEnabled(Boolean(res?.enabled && res?.configured)))
      .catch(() => setAiEnabled(false));
  }, []);

  const generate = async () => {
    try {
      setGenerating(true);
      const result = await onGenerate();
      onGenerated(result);
      onToast?.('AI analysis generated', 'success');
    } catch (e: any) {
      onError(e?.body?.message || 'Failed to generate AI analysis');
    } finally {
      setGenerating(false);
    }
  };

  if (aiEnabled === null) {
    return <EuiLoadingSpinner size="m" />;
  }

  return (
    <div>
      {!aiEnabled && (
        <EuiCallOut title="AI analysis is not configured" color="warning" iconType="alert">
          Set up an AI provider and API key under Settings &gt; AI analysis to enable this feature.
        </EuiCallOut>
      )}

      <EuiSpacer size="m" />

      {analysis ? (
        <EuiPanel paddingSize="m" hasBorder>
          <EuiText size="s" color="subdued">
            Generated by {analysis.provider}
            {analysis.model ? ` (${analysis.model})` : ''} at {new Date(analysis.generated_at).toLocaleString()}
          </EuiText>
          <EuiSpacer size="s" />
          <EuiText size="s" style={{ whiteSpace: 'pre-wrap' }}>
            {analysis.text}
          </EuiText>
        </EuiPanel>
      ) : (
        <EuiText size="s" color="subdued">
          {emptyMessage}
        </EuiText>
      )}

      <EuiSpacer size="m" />
      <EuiButton size="s" onClick={generate} isLoading={generating} isDisabled={!aiEnabled}>
        {analysis ? 'Regenerate analysis' : 'Generate AI analysis'}
      </EuiButton>
    </div>
  );
};
