// Generated by scripts/generate-build-info.js before yarn build.
export const PLUGIN_VERSION = "2.0.0";
export const TARGET_OSD_VERSION = "2.19.5";
export const PLUGIN_BUILD_ID = "2.0.0-20260828173306459-7454dd600dc2";
export const PLUGIN_BUILT_AT = "2026-08-28T17:33:06.459Z";
