// Generated by scripts/generate-build-info.js before yarn build.
export const PLUGIN_VERSION = "2.0.1";
export const TARGET_OSD_VERSION = "2.19.5";
export const PLUGIN_BUILD_ID = "2.0.1-20260829130329644-14557ab99673";
export const PLUGIN_BUILT_AT = "2026-08-29T13:03:29.644Z";
